### ISSUE TITLE
How is this repo different?

### ISSUE THREAD

**Issue by jhfoo** [OPHoperHPO/lilygo-ttgo-twatch-2020-micropython-lobo#1]
I note you have 2 firmware repos for the same TTgo 2020 watch. Can you help me understand what's the difference in the use case between them?

Ref: https://github.com/OPHoperHPO/lilygo-ttgo-twatch-2020-micropython

**Comment by OPHoperHPO** [comment]
I know about this.

1. OPHoperHPO/lilygo-ttgo-twatch-2020-micropython - port of official micropython branch

2. OPHoperHPO/lilygo-ttgo-twatch-2020-micropython**-lobo** - deprecated port with bugs and flaws of  Loboris Micropython
